name: consulting_snowflake_dbt
version: 1.0.0
config-version: 2
profile: consulting_snowflake_dbt
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  consulting-snowflake-dbt:
    +materialized: view
